version: 1.0
workflows:
    - name: run_gaudi
      subclass: WDL
      primaryDescriptorPath: /run_gaudi.wdl
      testParameterFiles:
          - /run_gaudi.json
workflows:
    - name: test
      subclass: WDL
      primaryDescriptorPath: /test.wdl
      testParameterFiles:
          - /test.json
